require "bundler/setup"
require "rake/testtask"
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:rspectest) do |t|
  t.pattern = ['rspecs/**/*_spec.rb', 'rspecs/**/*_test.rb']
end

Rake::TestTask.new(:minitest) do |t|
  t.libs << "minispecs"
  t.test_files = FileList['minispecs/**/*_spec.rb', 'minispecs/**/*_test.rb']
end

task default: [:minitest, :rspectest, :minitest_rake_task]

Rake::TestTask.new(:minitest_rake_task) do |t|
  t.test_files = FileList['test/minitest/*_test.rb']
end
