require "bundler/setup"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "minispecs"
  t.libs << "lib"
  t.test_files = FileList['minispecs/**/*_spec.rb']
end

task default: :test
